/* 光線特勤隊 課程資料：主選單（index.html）和積木島（world.html）共用。改日期、改步驟只要改這裡。 */
(function(){
    const LC="https://classtools1020.github.io/light-color/";
    const CK="https://classtools1020.github.io/games/checkin.html";
const LESSONS={
      A:{name:"課 A・白光的祕密",task:"任務三 光與顏色｜第1節 看懂母題",cp:"色散（白光藏七彩）＋選擇性反射（蘋果為什麼是紅的）",
        prep:["紅蘋果 1 顆","綠葉 1 片","藍色的東西 1 個","投影＋平板或手機（開相機用）","心情卡／完成貼紙"],
        steps:[["🧘 開場儀式：心情打卡＋光之泡泡呼吸",CK],["先暖身 30 秒",LC+"reflect-recap.html"],["簡報：白光是什麼顏色？","https://gamma.app/docs/cvet1x6jr7eyeh7"],["魔法相機：綠光下蘋果變黑",LC+"camera.html"],["光的舞臺",LC+"stage.html"],["顏色偵探大挑戰",LC+"detective.html"],["🚆 光之環島列車：從台北出發（推薦・溫和音效）","https://classtools1020.github.io/games/taiwan-train.html"],["🚂 光之列車闖關（火車地圖 8 站・扭蛋圖鑑）","https://classtools1020.github.io/games/light-train.html"],["🌙 收尾儀式：心情再打卡＋蓋章",CK+"#end"]],tip:"開相機前先說「畫面會變暗一下」；每個問題等 5 秒再點人；謎題先不解答。"},
      B:{name:"課 B・混光魔法・白光大解密",task:"任務三 光與顏色｜第2節 動手探究",cp:"光的三原色・加色混合：紅＋綠＋藍＝白光",
        prep:["LED 手電筒 3 支（或手機 3 支）","紅、綠、藍玻璃紙 各 1–2 張","橡皮筋 3 條","白牆或白板","圓點貼紙（紅綠藍黃白）","牛頓色盤（列印）＋彩色筆＋鉛筆或牙籤","教室能關燈（拉窗簾）"],
        steps:[["🧘 開場儀式：心情打卡＋光之泡泡呼吸",CK],["簡報（含影片）","https://gamma.app/docs/rzk98mghshheb2j"],["🎬 影片：螢幕放大看不是白色 1:44","https://www.youtube.com/watch?v=2j7oBDZOcbM"],["混光魔法：關燈儀式→先猜→驗證→開寶箱",LC+"mix-magic.html"],["🎬 影片：光的三原色一看就懂 1:29","https://www.youtube.com/watch?v=K4L-_1ybLzc"],["數位混光台","https://classtools1020.github.io/games/color-mixer.html"],["牛頓色盤：轉一轉變白色（列印＋數位）",LC+"newton-disc.html"],["學習單 🔵🟠（列印）",LC+"files/04_混光魔法_學習單_照片版.pdf"],["🌙 收尾儀式：心情再打卡＋蓋章",CK+"#end"]],tip:"關燈一定先說「數 3、2、1」；怕黑的同學先問要不要坐旁邊或安靜角。三支燈輪流拿，其他人當裁判。"},
      C:{name:"課 C・顏色偵探・結案報告",task:"任務三 光與顏色｜第3節 整理與應用",cp:"選擇性反射的生活決定：背心・白衣黑衣・紅綠燈",
        prep:["結案報告單（列印）","貼紙","平板或筆電（開前鏡頭：個人色彩鑑定）","選配：螢光背心或螢光黃紙、黑T＋白T"],
        steps:[["🧘 開場儀式：心情打卡＋光之泡泡呼吸",CK],["簡報（含影片）","https://gamma.app/docs/rtg4ii4w0kekctx"],["🎬 影片：為什麼東西有顏色（均一）播 0–2:30","https://www.youtube.com/watch?v=822JZAJiZ3I"],["結案關卡：三個生活案件",LC+"case-close.html"],["🎨 四季色彩鑑定所：你是春夏秋冬哪一種人？","personal-color/index.html"],["🎬 影片：反光背心的祕密 播 0–1:30","https://www.youtube.com/watch?v=nJVP2tpuNNc"],["🎬 影片：紅綠燈的由來 播 0–2:00","https://www.youtube.com/watch?v=oqvqH75A3MI"],["顏色大搶答","https://classtools1020.github.io/games/light-color-quiz.html"],["結案報告單（列印）",LC+"files/06_顏色偵探_結案報告單_照片版.pdf"],["🌙 收尾儀式：心情再打卡＋蓋章",CK+"#end"]],tip:"每破一案蓋章；三案全破按「結案」機器人會出來。乙班第 7 節若縮短，搶答與學習單做到哪算到哪。"},
      R1:{name:"第1節・吸管真的斷了嗎？",task:"任務四 光的折射｜看懂母題（Ka-IV-8）",cp:"光從空氣進到水裡，方向改變＝折射；看起來彎、看起來淺",prep:["透明杯 每桌 1 個","吸管 每桌 1 支","碗 1 個＋硬幣 1 枚","水盆 1 個＋10 元硬幣＋筷子 1 雙（真人撈硬幣）","水壺＋抹布","投影"],steps:[["🧘 開場儀式：心情打卡＋光之泡泡呼吸",CK],["🎵 暖身：光光在哪裡 MV（複習光源・影子・反射）","https://classtools1020.github.io/light-mv-teen.html"],["簡報：吸管斷了嗎？","https://gamma.app/docs/roocidjl8llmyvv"],["🎬 影片：光的折射 1:30 全播","https://www.youtube.com/watch?v=vncul9LxgT0"],["折射實驗室（三站）","https://classtools1020.github.io/light-refract/lab.html#lesson"],["📰 看新聞練習：女子河邊泡腳一腳踩空，靠「仰漂」獲救（三立）","https://www.setn.com/news/1892874"],["🎬 為什麼泳池底看起來比實際淺？（視深示範・只播實驗畫面）","https://www.youtube.com/watch?v=b22jveVteYk"],["📰 備用新聞：永和運動中心溺水事故（公視）","https://www.youtube.com/watch?v=g5HAVf66NWc"],["🎬 均一《光的折射》播 0–2:30","https://www.youtube.com/watch?v=JpgvgHPlK8s"],["學習單 🔵🟠（列印）","https://classtools1020.github.io/light-refract/files/04_折射_學習單_照片版.pdf"],["🎵 統整：折一下 Snap! MV（折射新歌）","https://classtools1020.github.io/light-refract/mv.html"],["🌙 收尾儀式：心情再打卡＋蓋章",CK+"#end"]],tip:"開場後先播光光在哪裡 MV（約 3 分鐘）暖身複習；新歌「折一下 Snap!」放在最後統整（歌詞會公布答案，不要開場放）。時間不夠就省略均一影片。謎題「吸管真的斷了嗎」先不解答等 8 秒；拿出吸管那一刻是高潮。硬幣魔術後接看新聞練習：先說「等一下是真的新聞，有人遇到危險，但最後被救起來了」，看完問 誰／在哪／發生什麼／為什麼／怎麼保護自己。"},
      R2:{name:"第2節・硬幣浮上來了！折射的魔法",task:"任務四 光的折射｜為什麼會折一下→命名→硬幣魔術→看新聞",cp:"光從空氣進到水裡速度變慢、在水面折一下、換方向＝折射；水看起來比較淺",prep:["透明杯＋吸管 1 組（回顧用）","碗 1 個＋10 元硬幣","水盆 1 個＋10 元硬幣＋筷子 1 雙（真人撈硬幣）","巧拼 2 塊（身體實驗的沙灘）","水壺＋抹布","黑板先寫：誰／哪裡／發生什麼／為什麼／怎麼辦"],steps:[["🧘 開場儀式：心情打卡＋光之泡泡呼吸",CK],["📽️ PPT 第2節（線上播放・有動畫）","https://view.officeapps.live.com/op/view.aspx?src=https%3A%2F%2Fclasstools1020.github.io%2Flight-refract%2Ffiles%2FR2-refraction.pptx"],["📖 折射偵探事件簿：吸管懸案＋光的規則","https://classtools1020.github.io/light-refract/story.html#straw"],["🪙 事件簿：硬幣魔術（先猜→倒水→揭曉）","https://classtools1020.github.io/light-refract/story.html#coin"],["🥢 真人版：水盆撈硬幣計分板（實驗室站 6）","https://classtools1020.github.io/light-refract/lab.html#lesson-6"],["🔎 事件簿：生活案件（泳池・撈魚・水滴）","https://classtools1020.github.io/light-refract/story.html#life"],["📺 光線新聞台：看新聞練習（仰漂獲救）","https://classtools1020.github.io/light-refract/news.html"],["🎵 首播！折一下 Snap! MV","https://classtools1020.github.io/light-refract/mv.html"],["🌙 收尾儀式：心情再打卡＋蓋章",CK+"#end"]],tip:"上一節只做到吸管實驗。事件簿用投影，按「揭曉」一步一步出現，上方章節可以直接跳。吸管懸案後做「手牽手走進巧拼沙灘」身體實驗（事件簿第 8 頁）。硬幣魔術一定先投票。新聞台第一句先說「主角最後平安獲救」。MV 放最後首播，Snap 的時候全班彈指。時間不夠：生活案件留到下一節。"},
      R3:{name:"第3節・折射動手做＋生活結案",task:"任務四 光的折射｜先猜→自己做→改答案＋生活應用（水滴放大鏡接任務五）",cp:"自己做出吸管彎、硬幣浮起；看見光束在水面折一下；水滴、魚缸、眼鏡也是光換方向",prep:["每桌：透明杯、吸管、碗、硬幣","水壺、抹布","老師：手電筒＋加幾滴牛奶的水（看得到光束）","滴管＋透明片＋報紙（水滴放大字）","列印包：規則卡、三步驟卡、預測貼紙、排序紀錄單"],steps:[["🧘 開場儀式：心情打卡＋光之泡泡呼吸",CK],["📽️ PPT 第3節（線上播放・有動畫）","https://view.officeapps.live.com/op/view.aspx?src=https%3A%2F%2Fclasstools1020.github.io%2Flight-refract%2Ffiles%2FR3-refraction.pptx"],["🎵 暖身：折一下 Snap! MV（按「副歌」一起彈指）","https://classtools1020.github.io/light-refract/mv.html"],["✋ 事件簿：動手做（先猜→做→改）","https://classtools1020.github.io/light-refract/story.html#hands"],["🖨️ 列印包・預測貼紙・排序紀錄單","https://classtools1020.github.io/light-refract/print-r2.html"],["🔦 看見光折一下（實驗室站 4）","https://classtools1020.github.io/light-refract/lab.html#lesson-4"],["🏙️ 光線小鎮・折射任務（3D 走街：吸管→硬幣→游泳池→竹東溪撈魚→一滴水）","https://classtools1020.github.io/light-town/#refract"],["🚆 折射環島搶答","https://classtools1020.github.io/games/light-refract-quiz.html"],["📝 學習單 🔵🟠（列印）","https://classtools1020.github.io/light-refract/files/04_折射_學習單_照片版.pdf"],["🏆 事件簿：結案報告","https://classtools1020.github.io/light-refract/story.html#end"],["🎵 結案慶祝：折一下 Snap! MV 全班合唱","https://classtools1020.github.io/light-refract/mv.html"],["🌙 收尾儀式：心情再打卡＋蓋章",CK+"#end"]],tip:"規則先講：水不打翻、手電筒不照眼睛。兩人一組輪流做吸管、硬幣；預測錯改貼不撕。牛奶水手電筒關燈前先說 3、2、1。若上一節沒上完生活案件，先開事件簿「生活案件」。光線小鎮：按「折射任務」，每站一位同學上台，撈魚那站故意先撈「看起來的魚」。時間不夠：搶答與學習單二選一。"},
      L1:{name:"第1節・放大鏡只會把東西變大嗎？",task:"任務五 透鏡｜看懂母題（翰林 4-4・Ka-IV-9）",cp:"中間厚＝凸透鏡：字變大、光會聚到焦點、遠處投影會倒過來；中間薄＝凹透鏡：字變小、光發散",prep:["放大鏡 每桌 1 支","凹透鏡或近視眼鏡 1–2 個","A4 白紙 每桌 2 張","窗簾拉一半（窗戶亮、教室後面暗）","手電筒 1 支","（選配）圓形透明水瓶＋畫箭頭的紙","學習單 🔵🟠 各一份（列印 3 頁）"],steps:[["🧘 開場儀式：心情打卡＋光之泡泡呼吸",CK],["📽️ PPT 透鏡第1節（線上播放・有動畫）","https://view.officeapps.live.com/op/view.aspx?src=https%3A%2F%2Fclasstools1020.github.io%2Flight-lens%2Ffiles%2FL1-lens.pptx"],["🏙️ 光線小鎮・透鏡任務（3D 走街：眼鏡行→教室投影→操場聚光→貓眼→一滴水）","https://classtools1020.github.io/light-town/#lens"],["透鏡實驗室（上課模式）","https://classtools1020.github.io/light-lens/lab.html#lesson"],["學習單 🔵🟠（列印）","https://classtools1020.github.io/light-lens/worksheet.html"],["🌙 收尾儀式：心情再打卡＋蓋章",CK+"#end"]],tip:"開場先做投影魔術：老師站教室後面用放大鏡把窗戶投在白紙上，謎題不揭曉。光線小鎮：按「透鏡任務」，每站請一位同學上台按，其他人先猜；第 2 站教室投影就是剛剛的魔術解答。放大鏡不對太陽、不對眼睛。名詞一次貼一張：凸透鏡、凹透鏡、焦點。"},
      SUBA:{name:"代課日・甲班：透鏡小偵探",task:"10/16 代課（甲班 第5節）｜複習透鏡＋放大鏡尋寶",cp:"放大鏡中間厚，讓光換方向，東西看起來變大",prep:["放大鏡","尋寶單（列印）"],steps:[["📽️ 10/16 代課簡報（線上播放）","https://view.officeapps.live.com/op/view.aspx?src=https%3A%2F%2Fclasstools1020.github.io%2Flight-refract%2F1016%2Fslides.pptx"],["🎵 MV〈折一下 Snap!〉","https://classtools1020.github.io/light-refract/mv.html"],["🔍 透鏡實驗室","https://classtools1020.github.io/light-lens/lab.html#lesson"],["📄 放大鏡尋寶單","https://classtools1020.github.io/light-refract/1016/treasure.pdf"],["🚆 折射環島搶答","https://classtools1020.github.io/games/light-refract-quiz.html"],["📋 代課流程單","https://classtools1020.github.io/light-refract/1016/plan.pdf"]],tip:"代課包網址與通關碼已私下給代課老師，10/16 16:00 下架；這裡是永久保存版。"},
      SUBB6:{name:"代課日・乙班：光線特勤隊總複習",task:"10/16 代課（乙班 第6節）｜光與顏色＋折射複習",cp:"光走直線，碰到水面折一下",prep:[],steps:[["📽️ 10/16 代課簡報（線上播放）","https://view.officeapps.live.com/op/view.aspx?src=https%3A%2F%2Fclasstools1020.github.io%2Flight-refract%2F1016%2Fslides.pptx"],["🎵 MV〈折一下 Snap!〉","https://classtools1020.github.io/light-refract/mv.html"],["🚆 光之環島列車","https://classtools1020.github.io/games/taiwan-train.html"],["🚆 折射環島搶答","https://classtools1020.github.io/games/light-refract-quiz.html"],["📋 代課流程單","https://classtools1020.github.io/light-refract/1016/plan.pdf"]],tip:"代課包網址與通關碼已私下給代課老師，10/16 16:00 下架；這裡是永久保存版。"},
      SUBB7:{name:"代課日・乙班：水滴放大鏡",task:"10/16 代課（乙班 第7節）｜生活裡的折射＋自己做水滴放大鏡",cp:"圓圓的水滴讓光換方向，字看起來變大",prep:["透明片、滴管、一杯水","尋寶單、畫卡（列印）"],steps:[["📽️ 10/16 代課簡報（線上播放）","https://view.officeapps.live.com/op/view.aspx?src=https%3A%2F%2Fclasstools1020.github.io%2Flight-refract%2F1016%2Fslides.pptx"],["🔎 生活裡的折射","https://classtools1020.github.io/light-refract/story.html#life"],["💧 水滴放大鏡（尋寶單）","https://classtools1020.github.io/light-refract/1016/treasure.pdf"],["🎨 「我看到的光」畫卡","https://classtools1020.github.io/light-refract/1016/draw.pdf"],["🎵 MV 再唱一次","https://classtools1020.github.io/light-refract/mv.html"],["📋 代課流程單","https://classtools1020.github.io/light-refract/1016/plan.pdf"]],tip:"代課包網址與通關碼已私下給代課老師，10/16 16:00 下架；這裡是永久保存版。乙班透鏡第 1 節順延到 10/21。"},
      REV:{name:"複習課・光與顏色＋月光",task:"複習（折射課順延一節）",cp:"複習任務三與中秋篇",prep:[],steps:[["🧘 開場儀式：心情打卡＋光之泡泡呼吸",CK],["🎵 光光在哪裡 MV","https://classtools1020.github.io/light-mv-teen.html"],["🌙 收尾儀式：心情再打卡＋蓋章",CK+"#end"]],tip:"這堂上複習，折射 R1 順延到 10/2。"},
      M:{name:"中秋特別篇・月亮會自己發光嗎？",task:"中秋特別任務｜光源・反射・月相（接任務一二）",cp:"月亮不是光源，是反射太陽光；中秋滿月＝太陽→地球→月亮排一直線",prep:["柚子 1 顆（當月亮；沒有就用淺色的球、橘子或白紙團）","手電筒 1 支（當太陽）","（可選）電子蠟燭 1 個","窗簾可拉暗","學習單（列印：🔵第1頁／🟠第2頁／答案卡第3頁）","破案貼紙"],steps:[["🧘 開場儀式：心情打卡＋光之泡泡呼吸",CK],["🎬 影片：滿月初升縮時 0:16 全播","https://www.youtube.com/watch?v=99Q8H1ygkk0"],["🌕 中秋月光之謎（謎題→暗房→分類→月相→月光列車→破案）","https://classtools1020.github.io/moon/"],["🎬 影片：月球的光是怎麼來的？（華視）1:03 全播・暗房後","https://www.youtube.com/watch?v=L9WeNTjX9oQ"],["🎬 影片：月相變化成因（LIS）3:57 全播・拖月亮前","https://www.youtube.com/watch?v=MdZs8VUiK_0"],["🏆 中秋月光大搶答（兩隊搶答・12 格）","https://classtools1020.github.io/moon/quiz.html"],["🙋 Baamboozle 中秋月光之謎（10 題）","https://www.baamboozle.com/game/4816616"],["📝 學習單 🔵🟠（列印）","https://classtools1020.github.io/moon/sheet.html"],["🌙 收尾儀式：心情再打卡＋蓋章",CK+"#end"]],tip:"📘 逐格教案台詞：classtools1020.github.io/moon/script.html。網頁左下「📖 老師台詞」每一幕都有逐句台詞與🔵🟠做法。拉窗簾前先說「3、2、1」。真人月相：一人當地球站中間、手電筒固定當太陽、柚子繞一圈。謎題答案最後才公布。9/25（五）中秋放假，折射課順延。"},
    };
    const SCHED=[
      {d:"2026-09-14",c:"甲班",p:"第7節 15:00–15:45",l:"A"},
      {d:"2026-09-16",c:"乙班",p:"第4節 11:05–11:50",l:"A"},{d:"2026-09-16",c:"甲班",p:"第7節 15:00–15:45",l:"B"},
      {d:"2026-09-18",c:"甲班",p:"第5節 13:10–13:55",l:"C"},{d:"2026-09-18",c:"乙班",p:"第6節 14:05–14:50",l:"B"},{d:"2026-09-18",c:"乙班",p:"第7節 15:00–15:45",l:"C"},
      {d:"2026-09-23",c:"乙班",p:"第4節 11:05–11:50",l:"M"},{d:"2026-09-23",c:"甲班",p:"第7節 15:00–15:45",l:"M"},
      {d:"2026-09-30",c:"乙班",p:"第4節 11:05–11:50",l:"REV"},{d:"2026-09-30",c:"甲班",p:"第7節 15:00–15:45",l:"REV"},
      {d:"2026-10-02",c:"甲班",p:"第5節 13:10–13:55",l:"R1"},{d:"2026-10-02",c:"乙班",p:"第6節 14:05–14:50",l:"R1"},{d:"2026-10-02",c:"乙班",p:"第7節 15:00–15:45",l:"R1"},
      {d:"2026-10-05",c:"甲班",p:"第7節 15:00–15:45",l:"R2"},
      {d:"2026-10-07",c:"乙班",p:"第4節 11:05–11:50",l:"R2"},{d:"2026-10-07",c:"甲班",p:"第7節 15:00–15:45",l:"R3"},
      {d:"2026-10-12",c:"甲班",p:"第7節 15:00–15:45",l:"L1"},
      {d:"2026-10-14",c:"乙班",p:"第4節 11:05–11:50",l:"R3"},
      {d:"2026-10-16",c:"甲班",p:"第5節 13:10–13:55",l:"SUBA"},{d:"2026-10-16",c:"乙班",p:"第6節 14:05–14:50",l:"SUBB6"},{d:"2026-10-16",c:"乙班",p:"第7節 15:00–15:45",l:"SUBB7"},
      {d:"2026-10-21",c:"乙班",p:"第4節 11:05–11:50",l:"L1"}
    ];
    window.LIGHT={LC,CK,LESSONS,SCHED};
})();
